DROP TABLE Account CASCADE;
DROP TABLE Game CASCADE;
DROP TABLE Records CASCADE;
DROP TABLE Location CASCADE;
DROP TABLE Mode CASCADE;
DROP TABLE Guess CASCADE;
DROP TABLE Play CASCADE;
DROP TABLE Element CASCADE;