import { Inter } from 'next/font/google'
import { Providers } from './providers'
import Navbar from './components/navbar'
import Footer from './components/footer'
import { getDisplayName } from 'next/dist/shared/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={
        {
          display: "flex",
          flexFlow: "column nowrap",
          minHeight: "100vh"
        }
      }>
        <Providers>
          <Navbar></Navbar>
          {children}
          <Footer></Footer></Providers></body>
    </html>
  )
}
